version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 488922825393.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - docker build -t lrcbp:latest .
      - docker tag lrcbp:latest 488922825393.dkr.ecr.eu-west-1.amazonaws.com/lrcbp:latest
  post_build:
    commands:
      - docker push 488922825393.dkr.ecr.eu-west-1.amazonaws.com/lrcbp:latest
      - printf '[{"name":"hello","imageUri":"%s"}]' 488922825393.dkr.ecr.eu-west-1.amazonaws.com/lrcbp > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json